config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :places do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
  root 'places#index'
  get  '/about',   to: 'pages#about'

  get  '/contact', to: 'pages#contact'

  get  '/edit',    to: 'places#edit'

  get  '/new',     to: 'places#new'

  get  '/show',    to: 'places#show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  searchkick
  mount_uploader :image, ImageUploader

  has_many :reviews

  validates :name, :city, :state, presence: true

  validates :state, format: {with: /\A[A-Z]{2}\z/,
    message: "must be in format: PA"}

  validates :website, format: {with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https://"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  validates :rating, :comment, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: "can only be whole number between 1 and 5"
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]

  def search
    if params[:search].present?
      @places = Place.search(params[:search])
    else
      @places = Place.all
    end
  end

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @reviews = Review.where(place_id: @place_id)
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @reviews = Review.where(place_id: @place.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :city, :state, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_place
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.place_id = @place.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @place, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to place_path(@place), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_place
      @place = Place.find(params[:place_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<%= image_tag "https://s3.amazonaws.com/placerater/Yelpbuildings.png", class:"footer_image" %>
<div class="copyright">
  <%= render html:"Jon Corrin ©2017" %>
</div>

app/views/layouts/_header.html.erb
<title>Place Rate</title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Place Rate", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Places <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Places", root_path %></li>
            <li><%= link_to "New Place", new_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <%= form_tag search_places_path, method: :get, class: "navbar-form navbar-left" do %>
          <p>
            <%= text_field_tag :search, params[:search], class: "form-control" %>
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          </p>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <%= render 'layouts/header' %>
  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container-fluid">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name =="notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;
            </span><span class ="sr-only">Close</span></button>
            <%= content_tag :div, msg, id:"flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
	   </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is Place Rate</h1>
<p>Rate the good eateries in your area!</p>

app/views/pages/contact.html.erb
<h1>For more information:</h1>
<p>rep@placerate.com</p>

app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
<% if place.errors.any? %>
  <div id="error-explanation", class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span></button>
    <h4><%= pluralize(place.errors.count, "error") %> prohibited this review from being saved:</h4>

    <ul>
    <% place.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <form>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", id: "inputName", placeholder: "Texas Steakhouse" %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control", id: "inputCity", placeholder: "Philadelphia" %>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control", id: "inputState", placeholder: "PA" %>
    </div>
    <div class="form-group">
      <%= f.label :website %>
      <%= f.text_field :website, class: "form-control", id: "inputWebsite", placeholder: "https://www.texassteakhouse.com" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </form>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place, class: "btn btn-link" %> |
<%= link_to 'Back', places_path, class: "btn btn-link"  %>

app/views/places/index.html.erb
  <p id="notice"><%= notice %></p>

  <div class="jumbotron">
    <h2>Place Rate is the best way to find places and rate them!</h2>
    <h3>Make sure to checkout and rate all of your favorite places.<br>
        Restaurants, gyms, you name it, we got it, you rate it.</h3>
  </div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place, review| %>
      <tr>
        <td><%= link_to place.name, place %></td>
        <td><%= place.city %></td>
        <td><%= place.state %></td>
        <td><%= link_to place.website, place.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Place', new_place_path, class: "btn btn-link"  %>
<% end %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path, class: "btn btn-link"  %>

app/views/places/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place %></td>
        <td><%= place.city %></td>
        <td><%= place.state %></td>
        <td><%= link_to place.website, place.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/show.html.erb
<div class="row">
  <div class="col-md-3">
    <% if @place.image_url.nil? %>
      <%= image_tag "https://s3.amazonaws.com/placerater/default.png" %>
    <% else %>
      <%= image_tag @place.image_url %>
    <% end %>
    <h2>
      <%= @place.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p>
      <% if @reviews.length == 1 %>
        <%= "#{@reviews.length} review" %>
      <% else %>
        <%= "#{@reviews.length} reviews" %>
      <% end %>
    </p>
    <p>
      <strong>City:</strong>
      <%= @place.city %>
    </p>
    <p>
      <strong>State:</strong>
      <%= @place.state %>
    </p>
    <p>
      <strong>Website:</strong>
      <%= link_to @place.website, @place.website %>
    </p>
    <%= link_to "Write a review", new_place_review_path(@place), class: "btn btn-primary" %>
    <br>
    <br>
    <iframe width="250" height="250" frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/place?q=<%= @place.city.parameterize %>&key=AIzaSyCOo5JybAUueilwSBmsuj1wc9F4LcIKrWc"&zoom=14 allowfullscreen></iframe>
  </div>

  <div class="col-md-9">
    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class ="col-md-9"></th>
          </tr>
        </thead>

        <tbody>
          <% @reviews.each do |review| %>
            <tr>
              <td>
                <h4>
                  <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
                </h4>
                <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
              </td>

              <td>
                <div class="star-rating" data-score= <%= review.rating %> ></div>
                <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>

                <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                    <%= link_to "Edit", edit_place_review_path(@place, review) %>
                    <%= link_to "Delete", place_review_path(@place, review), method: :delete %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/placerater/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>





<%= link_to 'Edit', edit_place_path(@place), class: "btn btn-link"  %> |
<%= link_to 'Back', places_path, class: "btn btn-link"  %>

app/views/reviews/_form.html.erb
<%= form_for([@place, @review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error-explanation", class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>
      <h4><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="star-rating"></div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: 'https://s3.amazonaws.com/placerater/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>


<%= link_to 'Back', place_path(@place)%>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', place_path(@place) %>